In [1]:
import numpy as np

In [2]:
# a ) Create an array of zeroes with size (3, 4)
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# b) Add 1 to elements in the first column, 2 to the second column, 3 to the third column and 4 to the fourth column
a = np.zeros((3,4))
b=a.T
print(b)
for i in range(4):
    b[i,:]=b[i,:]+np.full((3,),i+1)
print(b)
a=b.T
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [4]:
# c) Divide each column by the second column (second column should then be composed of ones)
c=b[1,:]
d=b/c
print(d)
print(d.T)

[[0.5 0.5 0.5]
 [1.  1.  1. ]
 [1.5 1.5 1.5]
 [2.  2.  2. ]]
[[0.5 1.  1.5 2. ]
 [0.5 1.  1.5 2. ]
 [0.5 1.  1.5 2. ]]


In [9]:
# d) 0-Pad the matrix (size 1)
e=np.pad(d.T,((1,1),(1,1)), 'constant', constant_values=(0))
print(e)

[[0.  0.  0.  0.  0.  0. ]
 [0.  0.5 1.  1.5 2.  0. ]
 [0.  0.5 1.  1.5 2.  0. ]
 [0.  0.5 1.  1.5 2.  0. ]
 [0.  0.  0.  0.  0.  0. ]]


In [ ]:
# e) Set to 0 all the non-diagonal values
for i in range (5):
    if e[]